module.exports = [
	{
		id: 1,
		name: 'Federal University Of Technology, Owerri(FUTO)',
		slug: 'federal-university-of-technology-owerri-111771818',
		userid: 1,
		mission:
			'To re-engineer and re-position the Federal University of Technology to be a truly world class university through recreating, nurturing and developing uniquely promising students and exceptional staff in Science, Technology and enterprise to the benefit of our globalized world.',
		motto: 'Technology for service',
		type: 'federal',
		category: 'university',
		alias: 'FUTO',
		established: 1980,
		founder: 'Federal Government',
		campus: 'urban',
		description:
			'FUTO, as the Oldest University of Technology in Nigeria, was established in 1980 by Executive fiat with the composition and appointment of the first provisional Council by Nigeria’s First Executive President, Shehu Shagari. It became the first of three such Universities set up by the Federal Government of Nigeria who sought to establish a University of Technology in each geo-political region and particularly in a State which did not have a conventional University.',
		website: 'https://futo.edu.ng/',
		history:
			'FUTO, as the Oldest University of Technology in Nigeria, was established in 1980 by Executive fiat with the composition and appointment of the first provisional Council by Nigeria’s First Executive President, Shehu Shagari. It became the first of three such Universities set up by the Federal Government of Nigeria who sought to establish a University of Technology in each geo-political region and particularly in a State which did not have a conventional University.',
		logo: 'https://futo.edu.ng/wp-content/uploads/2017/11/LogoMain-02.png',
		location: 'Owerri',
		state: 'Imo',
		mascot: 'Oil Rig',
		colors: 'Green and Yellow',
		school_head: 'Professor Francis Chukwuemeka Eze',
		latitude: 9.888,
		longitude: -10.999,
		email: 'info@futo.edu.ng',
		telephone: '+(234) 000 0000',
		pmb: 1526,
		school_photos: [
			'https://images.pexels.com/photos/207692/pexels-photo-207692.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
			'https://images.pexels.com/photos/256448/pexels-photo-256448.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
			'https://images.pexels.com/photos/2305098/pexels-photo-2305098.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
			'https://images.pexels.com/photos/333304/pexels-photo-333304.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260'
		],
		createdAt: new Date(),
		updatedAt: new Date(),
		commentCount: 2000,
		likeCount: 14,
		viewCount: 45,
		isDeleted: false,
		country: 'Nigeria',
		catchment_areas: [ 'IMO', 'ABIA', 'ENUGU', 'EBONYI', 'ANAMBRA', 'RIVERS' ]
	},
	{
		id: 2,
		slug: 'federal-university-of-technology-akure-216362132434',
		userid: 2,
		name: 'Federal University Of Technology, Akure(FUTA)',
		mission:
			'To promote technological advancement by providing conducive environment for research, teaching and learning engenders development of products that are technologically oriented, self-reliant and relevant to society',
		motto: 'Technology for service',
		type: 'federal',
		category: 'university',
		alias: 'FUTA',
		established: 1981,
		founder: 'Federal Government',
		campus: 'urban',
		description:
			'Federal University of Technology, Akure (FUTA), a top ranking University of technology in Nigeria and indeed the nations pride.Established in 1981, the university has grown tremendously, stretching its academic disciplines and research across eight different schools and over fifty academic departments.',
		history:
			'Federal University of Technology, Akure (FUTA), a top ranking University of technology in Nigeria and indeed the nations pride.Established in 1981, the university has grown tremendously, stretching its academic disciplines and research across eight different schools and over fifty academic departments.',
		website: 'https://futa.edu.ng/',
		logo:
			'https://i2.wp.com/www.naijabusiness.com.ng/wp-content/uploads/2019/06/Federal-University-of-Technology-Akure-FUTA-Logo.jpeg?resize=403%2C397&ssl=1',
		location: 'Akure',
		state: 'Ondo',
		mascot: 'Sunlight',
		colors: 'Green and Yellow',
		school_head: 'Professor Joseph Fuwape',
		latitude: 9.888,
		longitude: -10.999,
		email: 'info@futa.edu.ng',
		telephone: '+(234) 000 0000',
		pmb: 706,
		school_photos: [
			'https://images.pexels.com/photos/207692/pexels-photo-207692.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
			'https://images.pexels.com/photos/256448/pexels-photo-256448.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
			'https://images.pexels.com/photos/2305098/pexels-photo-2305098.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
			'https://images.pexels.com/photos/333304/pexels-photo-333304.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260'
		],
		createdAt: new Date(),
		updatedAt: new Date(),
		commentCount: 2000,
		likeCount: 14,
		viewCount: 45,
		isDeleted: false,
		country: 'Nigeria',
		catchment_areas: [ 'OGUN', 'EKITI', 'OYO', 'ONDO', 'OSUN', 'LAGOS' ]
	},
	{
		id: 3,
		slug: 'imo-state-university-127677842',
		userid: 2,
		name: 'Imo State University',
		mission:
			'Our primarily goals focuses on continuous provision of quality learning environment and producing highly intellectual graduates with reputable character',
		motto: '',
		type: 'state',
		category: 'university',
		alias: 'IMSU',
		established: 1981,
		founder: 'Imo State Government',
		campus: 'urban',
		description: 'The Imo State University (IMSU) in Owerri, Imo State, Nigeria was established in 1981.',
		history:
			'The Imo State University (IMSU) in Owerri, Imo State, Nigeria was established in 1981 through law No. 4 passed by the Imo State House of Assembly.The university admitted the first intake of 392 pioneer students on 23 October 1981.After the creation of Abia State in 1991, the Uturu campus of the university became the Abia State University. Imo State University is a fully functional university.Most of the programmes of the university have obtained full accreditation from National Universities Commission of Nigeria.The result of the 1999/2000 accreditation exercise of the National Universities Commission (NUC) confirmed the high rate and acceptance of the university by the Nigerian public. The university was ranked first among all state universities in Nigeria and the 10th overall among both state and federal universities.Imo State University at Owerri was temporary accommodated within the campus of Alvan Ikoku Federal College of Education from May to December 1992. The University later moved to its own premises of four building within the Federal University of Technology Owerri, at the Lake Nwaebere Campus. All the translocation of the Federal University to the permanent site, Ihiagwa near Owerri, the Lake Nwaebere Campus of that university was then acquired for Imo State University. The first batch of students was allocated to the Imo State University by JAMB in February 1993. The National Universities Commission also formally approved the re-establishment of the University in 1992 at the Lake Nwaebere Campus. Consequently, the government of Chief Evan Enwerem, in April, 1991 did not waste time in filling the vacuum by re- establishing the University in Owerri.Two options were considered by the government in the re - establishment of Imo State University at Owerri.The first option was to move at once, all staff and students at the various stages of their programmes in Uturu who want to remain in Imo State University, now in Owerri.The second option was to rebuild the University at Owerri over specified period of time.The second option was adopted after various constitutions by government then, and a target period of five years within which to complete re - establishment of the University at Owerri was considered.Professor T.O.C.Ndubizu, Deputy Vice - Chancellor, University of Nigeria, Nsukka was then appointed the Vice - Chancellor with the responsibility of relocating and re - establishing Imo State University.',
		website: 'www.imsu.edu.ng',
		logo:
			'https://i2.wp.com/www.naijabusiness.com.ng/wp-content/uploads/2019/06/Federal-University-of-Technology-Akure-FUTA-Logo.jpeg?resize=403%2C397&ssl=1',
		location: 'OWerri',
		state: 'Imo',
		mascot: 'Sunlight',
		colors: 'Green and Yellow',
		school_head: 'Victoria Adaobi Obasi',
		latitude: 9.888,
		longitude: -10.999,
		email: 'portal@imsu.edu.ng',
		telephone: '0806 527 8582, 0813 983 3300',
		pmb: 2000,
		school_photos: [
			'https://images.pexels.com/photos/207692/pexels-photo-207692.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
			'https://images.pexels.com/photos/256448/pexels-photo-256448.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
			'https://images.pexels.com/photos/2305098/pexels-photo-2305098.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
			'https://images.pexels.com/photos/333304/pexels-photo-333304.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260'
		],
		createdAt: new Date(),
		updatedAt: new Date(),
		commentCount: 2000,
		likeCount: 14,
		viewCount: 45,
		isDeleted: false,
		country: 'Nigeria',
		catchment_areas: [ 'OGUN', 'EKITI', 'OYO', 'ONDO', 'OSUN', 'LAGOS' ]
	},
	{
		id: 4,
		slug: 'imo-state-polytechnic-127677842',
		userid: 5,
		name: 'Imo State Polytechnic',
		mission:
			'To offer knowledge-based and hands-on skills training in science, technology, and innovative arts for self-reliance, food security, and sustainable development.',
		motto: '',
		type: 'state',
		category: 'polytechnic',
		alias: 'IP',
		established: 1978,
		founder: 'Imo State Government',
		campus: 'rural',
		description: 'Imo State Polytechnic is a higher education institute in Umuagwo, Imo State, Nigeria.',
		history:
			'Imo State Polytechnic is a higher education institute in Umuagwo, Imo State, Nigeria. It was established in 1978 as the Michael Okpara College of Agriculture, Umuagwo and was upgraded to a Polytechnic status, renamed as the Imo State Polytechnic, Umuagwo in 2007. The institution provides courses, training and research in all branches of Agriculture, Management Sciences, Engineering and Food Sciences.[1] The institution is certified to award National Diploma and Higher National Diploma qualifications.The Polytechnic is twenty-six kilometers from Owerri on the Port Harcourt road and has three hundred and sixty hectares of land. The Otamiri River runs past its border, making it ideal for all year round agricultural production through irrigation.Chinwe Obaji was a lecturer at this institution before being appointed head of the Nigerian Federal Ministry of Education.In 2009, the Rector, Dr.Anderson Amadioha, stated that "We have developed about 43 varieties of high yielding cassava stems for use by farmers."The college has also researched improvements to other crops, such as maize.',
		website: 'https://www.imopoly.edu.ng/',
		logo:
			'https://i2.wp.com/www.naijabusiness.com.ng/wp-content/uploads/2019/06/Federal-University-of-Technology-Akure-FUTA-Logo.jpeg?resize=403%2C397&ssl=1',
		location: 'Umuagwo-Ohaji',
		state: 'Imo',
		mascot: 'Sunlight',
		colors: 'Green and Yellow',
		school_head: 'Dr Patrick Ndionyenma Njoku',
		latitude: 9.888,
		longitude: -10.999,
		email: 'info@imopoly.edu.ng',
		telephone: '+234 (0) 703 6209 075',
		pmb: 2000,
		school_photos: [
			'https://images.pexels.com/photos/207692/pexels-photo-207692.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
			'https://images.pexels.com/photos/256448/pexels-photo-256448.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
			'https://images.pexels.com/photos/2305098/pexels-photo-2305098.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
			'https://images.pexels.com/photos/333304/pexels-photo-333304.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260'
		],
		createdAt: new Date(),
		updatedAt: new Date(),
		commentCount: 2000,
		likeCount: 14,
		viewCount: 45,
		isDeleted: false,
		country: 'Nigeria',
		catchment_areas: [ '' ]
	},
	{
		id: 5,
		slug: 'federal-polytechnic-nekede-127677842',
		userid: 5,
		name: 'Federal Polytechnic, Nekede',
		mission: 'To Be Pacesetters In Demand-Driven Technology And Innovations',
		motto: 'Knowledge and Skill for service',
		type: 'federal',
		category: 'polytechnic',
		alias: 'FEDPONEK',
		established: 1978,
		founder: 'Federal Government',
		campus: 'urban',
		description:
			'The Federal Polytechnic, Nekede is a federal government-owned higher institution located in Nekede, a town in Imo State, South-Eastern Nigeria',
		history:
			'The Federal Polytechnic, Nekede is a federal government-owned higher institution located in Nekede, a town in Imo State, South-Eastern Nigeria.It was established on a temporary site at the premise of Government Technical College by the Imo State government in 1978 as College of Technology, Owerri before it was moved to its present location in Nekede. On 7 April 1993, the polytechnic was changed to a federal government institution and was renamed "The Federal Polytechnic, Nekede".The Federal Polytechnic, Nekede offers National Diploma and Higher National Diploma courses at undergraduate levels.',
		website: 'https://fedpolynekede.edu.ng/',
		logo:
			'https://i2.wp.com/www.naijabusiness.com.ng/wp-content/uploads/2019/06/Federal-University-of-Technology-Akure-FUTA-Logo.jpeg?resize=403%2C397&ssl=1',
		location: 'Nekede',
		state: 'Imo',
		mascot: 'Sunlight',
		colors: 'Green and Yellow',
		school_head: 'Rev. Engr. Dr Micheal Arimanwa',
		latitude: 9.888,
		longitude: -10.999,
		email: 'info@fdpon.edu.ng',
		telephone: '(+234) 803-328-7500',
		pmb: 1036,
		school_photos: [
			'https://images.pexels.com/photos/207692/pexels-photo-207692.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
			'https://images.pexels.com/photos/256448/pexels-photo-256448.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500',
			'https://images.pexels.com/photos/2305098/pexels-photo-2305098.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
			'https://images.pexels.com/photos/333304/pexels-photo-333304.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260'
		],
		createdAt: new Date(),
		updatedAt: new Date(),
		commentCount: 200,
		likeCount: 14,
		viewCount: 45,
		isDeleted: false,
		country: 'Nigeria',
		catchment_areas: [ '' ]
	}
];
